//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HashTagTweetMap
    {
        public int HashTagTweetMapId { get; set; }
        public int TweetId { get; set; }
        public int HashTagId { get; set; }
    
        public virtual HashTag HashTag { get; set; }
        public virtual Tweet Tweet { get; set; }
    }
}
