//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reaction
    {
        public int ReactionId { get; set; }
        public int UserId { get; set; }
        public int TweetId { get; set; }
        public Nullable<bool> LikeFlag { get; set; }
    
        public virtual Tweet Tweet { get; set; }
        public virtual User User { get; set; }
    }
}
